import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {flushSync} from 'react-dom';
const f=(v,n=1)=>typeof v==='number'&&Number.isFinite(v)?v.toLocaleString('en',{maximumFractionDigits:n}):'—';
const labels={rain:'Rainfall',temp:'Temperature',humidity:'Humidity',wind:'Wind',pressure:'Pressure',q:'Discharge'};
function Panel({title,note,children}){return <section className="card"><div className="card-head"><div><h2>{title}</h2>{note&&<p>{note}</p>}</div></div><div className="card-body">{children}</div></section>}
function Bars({items,unit=''}){const peak=Math.max(1,...items.map(x=>Math.abs(x.value||0)));return <div className="bar-list">{items.map((x,i)=><div className="bar-item" key={i}><span>{x.label}</span><div className="bar-track"><div className="bar-fill" style={{width:100*Math.abs(x.value||0)/peak+'%'}}/></div><span>{f(x.value)} {unit}</span></div>)}</div>}
function Table({heads,rows}){return <div className="table-wrap"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>}
function AnnualRateChart({years}){const W=720,H=260,p={l:48,r:18,t:22,b:44},iw=W-p.l-p.r,ih=H-p.t-p.b,max=Math.max(10,...years.map(x=>x.rate||0))*1.12,x=i=>p.l+(years.length<2?iw/2:i*iw/(years.length-1)),y=v=>p.t+ih-(v||0)*ih/max;return <svg className="analysis-chart" viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Annual unusual day rate line chart"><text x={p.l} y={14}>Unusual days (%)</text>{[0,.5,1].map((t,i)=><g key={i}><line className="chart-grid" x1={p.l} x2={W-p.r} y1={y(max*t)} y2={y(max*t)}/><text x={p.l-8} y={y(max*t)+4} textAnchor="end">{Math.round(max*t)}%</text></g>)}<polyline fill="none" stroke="#0d8584" strokeWidth="3" points={years.map((a,i)=>`${x(i)},${y(a.rate)}`).join(' ')}/>{years.map((a,i)=><g key={a.year}><circle cx={x(i)} cy={y(a.rate)} r="5" fill="#0d8584"><title>{a.year}: {f(a.rate,1)}% unusual days{a.partial?' (partial year)':''}</title></circle><text x={x(i)} y={H-16} textAnchor="middle">{String(a.year).slice(2)}{a.partial?'*':''}</text></g>)}</svg>}
function ScreeningChart({ranking}){const items=ranking.slice(0,15),W=720,row=30,H=items.length*row+28,max=100;return <><svg className="analysis-chart" viewBox={`0 0 ${W} ${H}`} role="img" aria-label="District screening score bar chart">{items.map((a,i)=>{const yy=i*row+8,w=510*a.score/max,color=a.basis.includes('available weights rescaled')?'#d29a3b':'#198a8a';return <g key={a.id}><text x="0" y={yy+15}>{a.district}</text><rect x="132" y={yy} width="510" height="15" rx="3" fill="#edf3f5"/><rect x="132" y={yy} width={w} height="15" rx="3" fill={color}><title>{a.district}: {f(a.score,0)} · {a.basis}</title></rect><text x="652" y={yy+13} textAnchor="end">{f(a.score,0)}</text></g>})}</svg><div className="legend"><span><i style={{background:'#198a8a'}}/>Full weighted score</span><span><i style={{background:'#d29a3b'}}/>Fallback with rescaled weights</span></div></>}
function ScatterChart({points}){const W=720,H=300,p={l:52,r:20,t:24,b:48},iw=W-p.l-p.r,ih=H-p.t-p.b,xmax=Math.max(1,...points.map(a=>a.rain||0)),ymax=Math.max(1,...points.map(a=>a.flow||0)),lx=v=>Math.log1p(v)/Math.log1p(xmax),ly=v=>Math.log1p(v)/Math.log1p(ymax);return <svg className="analysis-chart" viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Rainfall and river discharge scatter plot"><text x={p.l} y={15}>Daily rainfall vs discharge · log scale</text><line x1={p.l} y1={p.t+ih} x2={p.l+iw} y2={p.t+ih} stroke="#cbd9df"/><line x1={p.l} y1={p.t} x2={p.l} y2={p.t+ih} stroke="#cbd9df"/><text x={p.l+iw/2} y={H-10} textAnchor="middle">Rainfall (mm)</text><text x="14" y={p.t+ih/2} transform={`rotate(-90 14 ${p.t+ih/2})`} textAnchor="middle">Discharge (m³/s)</text>{[0,.5,1].map((t,i)=><g key={i}><line className="chart-grid" x1={p.l} x2={p.l+iw} y1={p.t+ih-ih*t} y2={p.t+ih-ih*t}/><text x={p.l-8} y={p.t+ih-ih*t+4} textAnchor="end">{f(Math.expm1(ymax*t),0)}</text><text x={p.l+iw*t} y={p.t+ih+20} textAnchor="middle">{f(Math.expm1(xmax*t),0)}</text></g>)}{points.map((a,i)=><circle key={i} cx={p.l+iw*lx(a.rain)} cy={p.t+ih-ih*ly(a.flow)} r="2.7" fill="#177e9a" opacity=".48"><title>{f(a.rain,1)} mm rain · {f(a.flow,1)} m³/s discharge</title></circle>)}</svg>}
function SeasonalityHeatmap({data,metric}){const years=[...new Set(data.map(a=>a.year))].sort((a,b)=>a-b),months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],key=metric==='rain'?'rain_mean':metric==='flow'?'flow_mean':'unusual_rate',values=data.map(a=>a[key]).filter(Number.isFinite),min=Math.min(...values),max=Math.max(...values),W=80+years.length*44,H=months.length*24+38,value=(y,m)=>data.find(a=>a.year===y&&a.month===m)?.[key],color=v=>{if(!Number.isFinite(v))return '#edf3f5';const t=max===min?.5:(v-min)/(max-min);return `hsl(${190-165*t} ${55+20*t}% ${90-38*t}%)`};return <svg className="analysis-chart heatmap" viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Monthly seasonality heatmap"><text x="0" y="13">{metric==='rain'?'Mean rainfall (mm/day)':metric==='flow'?'Mean discharge (m³/s)':'Unusual-day rate (%)'}</text>{years.map((yr,i)=><text key={yr} x={80+i*44+18} y="30" textAnchor="middle">{yr}</text>)}{months.map((m,mi)=><g key={m}><text x="0" y={48+mi*24}>{m}</text>{years.map((yr,yi)=>{const v=value(yr,mi+1);return <rect key={yr} x={80+yi*44} y={36+mi*24} width="36" height="18" rx="3" fill={color(v)}><title>{yr} {m}: {f(v,1)}{metric==='rain'?' mm':metric==='flow'?' m³/s':'%'}</title></rect>})}</g>)}</svg>}
function CalendarHeatmap({data}){const years=[...new Set(data.map(a=>a.date.slice(0,4)))].sort(),byDate=new Map(data.map(a=>[a.date,a.severity])),W=720,H=years.length*28+40,colors=['#e7f1f2','#e8b65b','#c95348'];return <><svg className="analysis-chart calendar" viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Extreme condition calendar heatmap"><text x="0" y="14">Daily condition severity · 2021 onward</text>{years.map((year,yi)=>{const jan=Date.UTC(Number(year),0,1);return <g key={year}><text x="0" y={39+yi*28}>{year}</text>{Array.from({length:53},(_,week)=>{const cells=[];for(let day=0;day<7;day++){const n=week*7+day,date=new Date(jan+n*86400000).toISOString().slice(0,10);if(date.slice(0,4)!==year)continue;const s=byDate.get(date),fill=s===2?colors[2]:s===1?colors[1]:s===0?colors[0]:'#f5f7f8';cells.push(<rect key={date} x={50+week*12} y={27+yi*28+day*2.7} width="10" height="2.5" rx="1" fill={fill}><title>{date}: {s===2?'unusual':s===1?'elevated':s===0?'typical':'missing'}</title></rect>)}return cells})}</g>})}</svg><div className="legend"><span><i style={{background:'#e7f1f2'}}/>Typical</span><span><i style={{background:'#e8b65b'}}/>Elevated</span><span><i style={{background:'#c95348'}}/>Unusual</span></div></>}
export function Analysis({summary,location,onLocation}){
 const [all,setAll]=useState(null),[error,setError]=useState(''),[metric,setMetric]=useState('rain'),[heatMetric,setHeatMetric]=useState('rain');
 useEffect(()=>{let active=true;const base=window.FLOODLENS_CONFIG?.apiBase;fetch(base?base+'/api/analysis':'data/eda.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(j=>{if(active)setAll(j)}).catch(()=>{if(active)setError('The analysis dataset is unavailable. Run pipeline/eda.py after collection.');});return()=>{active=false}},[]);
 if(error)return <Panel title="Analysis unavailable">{error}</Panel>;
 if(!all)return <p role="status">Loading exploratory analysis…</p>;
 const d=all.locations[location];if(!d)return <Panel title="Location pending">This location has not been processed yet.</Panel>;
 const stats=d.statistics[metric],keys=Object.keys(labels);
 return <><div className="info-strip">Full available archive · {summary.start} to {summary.end}. These analyses use district reference points. Forecast values are excluded.</div>
 <div className="two-grid"><Panel title="Distribution & summary" note="Daily values; missing records are excluded, never replaced by zero."><label>Variable <select value={metric} onChange={e=>setMetric(e.target.value)}>{keys.map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label><Table heads={['Valid days','Mean','Median','Std. deviation','95th percentile']} rows={[[stats.n,f(stats.mean),f(stats.median),f(stats.std),f(stats.p95)]]}/><Bars items={d.histograms[metric].map(b=>({label:b.label,value:b.count}))} unit="days"/></Panel>
 <Panel title="Correlation matrix" note="Pearson correlation of paired daily records. Raw correlations can reflect seasonality; they do not establish causation."><Table heads={['Variable',...keys.map(k=>labels[k])]} rows={keys.map(k=>[labels[k],...keys.map(j=><span title={`${d.correlation_counts[k][j]} paired days`} style={{color:(d.correlations[k][j]||0)<0?'#a53e36':'#07676c'}}>{f(d.correlations[k][j],2)}</span>)])}/></Panel></div>
 <div className="two-grid"><Panel title="Monsoon comparison" note="Southwest: May–September. Northeast: November–January. Per-day means allow comparison across different season lengths."><Table heads={['Season','Valid rain days','Mean rain mm/day','Mean flow m³/s','Unusual-day rate']} rows={d.monsoons.map(x=>[x.season,x.rain_days,f(x.rain_mean),f(x.flow_mean),f(x.unusual_rate)+'%'])}/></Panel><Panel title="Extreme conditions by year" note="Post-baseline years. Partial years are marked; compare rates as well as counts."><Table heads={['Year','Valid days','Unusual days','Rate','Flow exceedance days']} rows={d.years.map(x=>[x.year+(x.partial?' (partial)':''),x.days,x.unusual_days,f(x.rate)+'%',x.flow_days])}/></Panel></div>
 <div className="two-grid"><Panel title="Annual unusual-day rate" note="Share of valid post-baseline days classified as unusual. Asterisk = partial year."><AnnualRateChart years={d.years}/></Panel><Panel title="District screening scores" note="Top locations on the latest historical day; rain-only scores are shown in amber."><ScreeningChart ranking={all.ranking}/></Panel></div>
 <div className="two-grid"><Panel title="Rainfall–discharge relationship" note="Pairwise daily values for this reference point. Log axes make rare high-flow events visible without hiding ordinary days."><ScatterChart points={d.scatter}/><p className="small-note">The pattern is exploratory association, not proof that local rainfall causes downstream discharge.</p></Panel><Panel title="Monthly seasonality heatmap" note="Compare calendar-month conditions across the full archive."><label className="chart-control">Measure <select value={heatMetric} onChange={e=>setHeatMetric(e.target.value)}><option value="rain">Mean rainfall</option><option value="flow">Mean discharge</option><option value="unusual">Unusual-day rate</option></select></label><SeasonalityHeatmap data={d.monthly} metric={heatMetric}/></Panel></div>
 <Panel title="Extreme-condition calendar" note="Each mark is one day from 2021 onward. Colour reflects the existing severity classification: typical, elevated, or unusual."><CalendarHeatmap data={d.calendar}/></Panel>
 <Panel title="District screening score" note="0–100 index on the latest historical day: 50% flood severity, 30% 3-day cumulative rainfall and 20% unusual weather (maximum temperature or wind percentile). Missing components are omitted and the remaining weights are rescaled. This is not a flood probability or an official warning."><Table heads={['District / reference point','Score','Basis','Elevation (m)','Latest day']} rows={all.ranking.map(x=>[<button className="table-button" onClick={()=>onLocation(x.id)}>{x.district} · {x.name}</button>,f(x.score,0),x.basis,f(x.elevation),x.date])}/></Panel></>;
}
async function json(url){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),30000);try{const r=await fetch(url,{signal:ctl.signal});if(!r.ok)throw Error(`Request failed (${r.status})`);const j=await r.json();if(j.error)throw Error(j.reason);return j}finally{clearTimeout(timer)}}
export function GlobalExplorer(){
 const [query,setQuery]=useState(''),[lat,setLat]=useState('6.927'),[lon,setLon]=useState('79.861'),[results,setResults]=useState([]),[status,setStatus]=useState(''),[place,setPlace]=useState(null),[global,setGlobal]=useState(false),[busy,setBusy]=useState(false);
 const ref=useRef(null),mapRef=useRef(null),markerRef=useRef(null),version=useRef(0);
 useEffect(()=>{if(!window.L)return;const L=window.L,m=L.map(ref.current,{scrollWheelZoom:false}).setView([7.85,80.7],7);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(m);m.on('click',e=>{setLat(e.latlng.lat.toFixed(5));setLon(e.latlng.lng.toFixed(5));setStatus('Coordinates selected. Choose “Load location” to retrieve the forecast.');});mapRef.current=m;return()=>{version.current++;m.remove();mapRef.current=null}},[]);
 useEffect(()=>{mapRef.current?.setView(global?[15,20]:[7.85,80.7],global?2:7)},[global]);
 async function search(){if(query.trim().length<2){setStatus('Enter at least two characters.');return}setBusy(true);setStatus('Searching…');try{const base=window.FLOODLENS_CONFIG?.apiBase;const j=await json(base?base+'/api/search?'+new URLSearchParams({name:query}):'https://geocoding-api.open-meteo.com/v1/search?'+new URLSearchParams({name:query,count:12,language:'en',format:'json',...(!global?{countryCode:'LK'}:{})}));setResults((j.results||[]).filter(x=>global||x.country_code==='LK'));setStatus((j.results||[]).length?'Select a search result.':'No places found. Try a nearby town.')}catch(e){setStatus(e.message)}finally{setBusy(false)}}
 async function load(a=lat,b=lon,name='Selected coordinates'){
  const latitude=Number(a),longitude=Number(b);if(String(a).trim()===''||String(b).trim()===''||!Number.isFinite(latitude)||!Number.isFinite(longitude)||Math.abs(latitude)>90||Math.abs(longitude)>180){setStatus('Enter valid latitude (−90 to 90) and longitude (−180 to 180).');return}
  const token=++version.current;setBusy(true);setPlace(null);setStatus('Retrieving weather, river flow and elevation…');setLat(String(latitude));setLon(String(longitude));
  if(mapRef.current){mapRef.current.setView([latitude,longitude],9);markerRef.current?.remove();markerRef.current=window.L.marker([latitude,longitude]).addTo(mapRef.current)}
  try{let value;const base=window.FLOODLENS_CONFIG?.apiBase,p={latitude,longitude};if(base){value=await json(base+'/api/place?'+new URLSearchParams(p))}else{const specs=[['weather','https://api.open-meteo.com/v1/forecast',{...p,current:'temperature_2m,relative_humidity_2m,wind_speed_10m,pressure_msl',daily:'precipitation_sum,temperature_2m_max,temperature_2m_min,wind_speed_10m_max',forecast_days:16,timezone:'GMT'}],['flood','https://flood-api.open-meteo.com/v1/flood',{...p,daily:'river_discharge_median,river_discharge_p25,river_discharge_p75',models:'forecast_v4',forecast_days:16}],['elevation','https://api.open-meteo.com/v1/elevation',p]];const r=await Promise.allSettled(specs.map(([,u,ps])=>json(u+'?'+new URLSearchParams(ps))));value={errors:{}};r.forEach((v,i)=>{value[specs[i][0]]=v.status==='fulfilled'?v.value:null;if(v.status==='rejected')value.errors[specs[i][0]]='Unavailable'});}if(token!==version.current)return;setPlace({...value,name,retrieved:new Date().toISOString()});setStatus(Object.keys(value.errors||{}).length?'Some providers are unavailable; available results are shown.':'Location updated.')}catch(e){if(token===version.current)setStatus(e.message)}finally{if(token===version.current)setBusy(false)}
 }
 function gps(){if(!navigator.geolocation){setStatus('GPS is not supported in this browser.');return}setStatus('Requesting your location…');navigator.geolocation.getCurrentPosition(p=>load(p.coords.latitude,p.coords.longitude,'Your location'),()=>setStatus('Location permission denied or GPS unavailable. Enter coordinates instead.'),{timeout:15000,maximumAge:60000})}
 const d=place?.weather?.daily,fd=place?.flood?.daily;
 return <><Panel title="Explore a location" note="Search within Sri Lanka or switch to the global map. Click the map to select coordinates."><div className="explorer-controls"><label><input type="checkbox" checked={global} onChange={e=>setGlobal(e.target.checked)}/> Global view</label><label>Place name<input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')search()}} placeholder={global?'Search a city worldwide':'Search Sri Lanka'}/></label><button className="button" disabled={busy} onClick={search}>Search</button><button className="button" onClick={gps} disabled={busy}>Use my GPS</button></div><div className="search-results">{results.map(p=><button className="chip" key={p.id} disabled={busy} onClick={()=>load(p.latitude,p.longitude,`${p.name}, ${p.country}`)}>{p.name} · {p.admin1} · {p.country}</button>)}</div><div className="explorer-controls"><label>Latitude<input type="number" step="any" min="-90" max="90" value={lat} onChange={e=>setLat(e.target.value)}/></label><label>Longitude<input type="number" step="any" min="-180" max="180" value={lon} onChange={e=>setLon(e.target.value)}/></label><button className="button" disabled={busy} onClick={()=>load()}>Load location</button></div><p role="status">{status}</p><div ref={ref} className="global-map" aria-label="Interactive world map"/></Panel>
 {place&&<Panel title={place.name} note={`Retrieved ${place.retrieved}. Forecast days use UTC.`}><div className="stats"><div><strong>{f(place.weather?.current?.temperature_2m)} °C</strong><p>Current modelled temperature</p></div><div><strong>{f(place.elevation?.elevation?.[0])} m</strong><p>Terrain elevation · 90 m DEM</p></div><div><strong>{f(place.weather?.current?.relative_humidity_2m)}%</strong><p>Current humidity</p></div><div><strong>{f(place.weather?.current?.wind_speed_10m)} km/h</strong><p>Current wind</p></div></div><Table heads={['UTC date','Rain mm','Min / max °C','Max wind km/h','Median flow m³/s','Flow P25–P75']} rows={(d?.time||fd?.time||[]).map((date,i)=>{const fi=fd?.time?.indexOf(date)??-1;return [date,f(d?.precipitation_sum?.[i]),`${f(d?.temperature_2m_min?.[i])} / ${f(d?.temperature_2m_max?.[i])}`,f(d?.wind_speed_10m_max?.[i]),f(fd?.river_discharge_median?.[fi]),`${f(fd?.river_discharge_p25?.[fi])}–${f(fd?.river_discharge_p75?.[fi])}`]})}/><p className="small-note">River output represents a nearby model grid and may select a different channel. Elevation alone does not measure flood vulnerability. Historical screening scores are available only for the 25 district reference points. Forecast ensemble percentiles are not return-period thresholds.</p></Panel>}</>;
}
let root;
export function mountView(element,{route,html,summary,location,onLocation}){if(!root)root=createRoot(element);flushSync(()=>root.render(route==='analysis'?<Analysis summary={summary} location={location} onLocation={onLocation}/>:route==='explore'?<GlobalExplorer/>:<div key={route+':'+html.length} dangerouslySetInnerHTML={{__html:html}}/>));}
