import React,{useState,useEffect,useRef} from 'react';
import {f,labels,Panel,Bars,Table,AnnualRateChart,ScatterChart,SeasonalityHeatmap,CalendarHeatmap} from '../components/analysis-charts.jsx';
export function Analysis({summary,location}){
 const [all,setAll]=useState(null),[error,setError]=useState(''),[metric,setMetric]=useState('rain'),[heatMetric,setHeatMetric]=useState('rain');
 useEffect(()=>{let active=true;fetch('data/eda.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(j=>{if(active)setAll(j)}).catch(()=>{if(active)setError('The analysis dataset is unavailable. Run pipeline/eda.py after collection.');});return()=>{active=false}},[]);
 if(error)return <Panel title="Analysis unavailable">{error}</Panel>;
 if(!all)return <p role="status">Loading exploratory analysis…</p>;
 const d=all.locations[location];if(!d)return <Panel title="Location pending">This location has not been processed yet.</Panel>;
 const stats=d.statistics[metric],keys=Object.keys(labels);
 return <><div className="info-strip">Full available archive · {summary.start} to {summary.end}. These analyses use district reference points. Forecast values are excluded.</div>
 <div className="two-grid"><Panel title="Distribution & summary" note="Daily values; missing records are excluded, never replaced by zero."><label>Variable <select value={metric} onChange={e=>setMetric(e.target.value)}>{keys.map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label><Table heads={['Valid days','Mean','Median','Std. deviation','95th percentile']} rows={[[stats.n,f(stats.mean),f(stats.median),f(stats.std),f(stats.p95)]]}/><Bars items={d.histograms[metric].map(b=>({label:b.label,value:b.count}))} unit="days"/></Panel>
 <Panel title="Correlation matrix" note="Pearson correlation of paired daily records. Raw correlations can reflect seasonality; they do not establish causation."><Table heads={['Variable',...keys.map(k=>labels[k])]} rows={keys.map(k=>[labels[k],...keys.map(j=><span title={`${d.correlation_counts[k][j]} paired days`} style={{color:(d.correlations[k][j]||0)<0?'#a53e36':'#07676c'}}>{f(d.correlations[k][j],2)}</span>)])}/></Panel></div>
 <div className="two-grid"><Panel title="Monsoon comparison" note="Southwest: May–September. Northeast: November–January. Per-day means allow comparison across different season lengths."><Table heads={['Season','Valid rain days','Mean rain mm/day','Mean flow m³/s','Unusual-day rate']} rows={d.monsoons.map(x=>[x.season,x.rain_days,f(x.rain_mean),f(x.flow_mean),f(x.unusual_rate)+'%'])}/></Panel><Panel title="Extreme conditions by year" note="Full archive years. Partial years are marked; compare rates as well as counts."><Table heads={['Year','Valid days','Unusual days','Rate','Flow exceedance days']} rows={d.years.map(x=>[x.year+(x.partial?' (partial)':''),x.days,x.unusual_days,f(x.rate)+'%',x.flow_days])}/></Panel></div>
 <div className="two-grid"><Panel title="Annual unusual-day rate" note="Share of valid full-archive days classified as unusual. Asterisk = partial year."><AnnualRateChart years={d.years}/></Panel></div>
 <div className="two-grid"><Panel title="Rainfall–discharge relationship" note="Pairwise daily values for this reference point. Log axes make rare high-flow events visible without hiding ordinary days."><ScatterChart points={d.scatter}/><p className="small-note">The pattern is exploratory association, not proof that local rainfall causes downstream discharge.</p></Panel><Panel title="Monthly seasonality heatmap" note="Compare calendar-month conditions across the full archive."><label className="chart-control">Measure <select value={heatMetric} onChange={e=>setHeatMetric(e.target.value)}><option value="rain">Mean rainfall</option><option value="flow">Mean discharge</option><option value="unusual">Unusual-day rate</option></select></label><SeasonalityHeatmap data={d.monthly} metric={heatMetric}/></Panel></div>
 <Panel title="Extreme-condition calendar" note="Each mark is one day from 2016 onward. Colour reflects the existing severity classification: typical, elevated, or unusual."><CalendarHeatmap data={d.calendar}/></Panel>
}
