import React,{useState,useEffect,useRef} from 'react';
import {f,Panel,Table} from '../components/analysis-charts.jsx';
import {fetchJSON} from '../lib/api.js';
export function GlobalExplorer(){
 const [query,setQuery]=useState(''),[lat,setLat]=useState('6.927'),[lon,setLon]=useState('79.861'),[results,setResults]=useState([]),[status,setStatus]=useState(''),[place,setPlace]=useState(null),[global,setGlobal]=useState(false),[busy,setBusy]=useState(false);
 const ref=useRef(null),mapRef=useRef(null),markerRef=useRef(null),version=useRef(0);
 useEffect(()=>{if(!window.L)return;const L=window.L,m=L.map(ref.current,{scrollWheelZoom:false}).setView([7.85,80.7],7);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(m);m.on('click',e=>{setLat(e.latlng.lat.toFixed(5));setLon(e.latlng.lng.toFixed(5));setStatus('Coordinates selected. Choose “Load location” to retrieve the forecast.');});mapRef.current=m;return()=>{version.current++;m.remove();mapRef.current=null}},[]);
 useEffect(()=>{mapRef.current?.setView(global?[15,20]:[7.85,80.7],global?2:7)},[global]);
 async function search(){if(query.trim().length<2){setStatus('Enter at least two characters.');return}setBusy(true);setStatus('Searching…');try{const j=await fetchJSON('https://geocoding-api.open-meteo.com/v1/search?'+new URLSearchParams({name:query,count:12,language:'en',format:'json',...(!global?{countryCode:'LK'}:{})}));setResults((j.results||[]).filter(x=>global||x.country_code==='LK'));setStatus((j.results||[]).filter(x=>global||x.country_code==='LK').length?'Select a search result.':'No places found. Try a nearby town.')}catch(e){setStatus(e.message)}finally{setBusy(false)}}
 async function load(a=lat,b=lon,name='Selected coordinates'){
  const latitude=Number(a),longitude=Number(b);if(String(a).trim()===''||String(b).trim()===''||!Number.isFinite(latitude)||!Number.isFinite(longitude)||Math.abs(latitude)>90||Math.abs(longitude)>180){setStatus('Enter valid latitude (−90 to 90) and longitude (−180 to 180).');return}
  const token=++version.current;setBusy(true);setPlace(null);setStatus('Retrieving weather, river flow and elevation…');setLat(String(latitude));setLon(String(longitude));
  if(mapRef.current){mapRef.current.setView([latitude,longitude],9);markerRef.current?.remove();markerRef.current=window.L.marker([latitude,longitude]).addTo(mapRef.current)}
  try{let value;const p={latitude,longitude};{const specs=[['weather','https://api.open-meteo.com/v1/forecast',{...p,current:'temperature_2m,relative_humidity_2m,wind_speed_10m,pressure_msl',daily:'precipitation_sum,temperature_2m_max,temperature_2m_min,wind_speed_10m_max',forecast_days:16,timezone:'GMT'}],['flood','https://flood-api.open-meteo.com/v1/flood',{...p,daily:'river_discharge_median,river_discharge_p25,river_discharge_p75',models:'forecast_v4',forecast_days:16}],['elevation','https://api.open-meteo.com/v1/elevation',p]];const r=await Promise.allSettled(specs.map(([,u,ps])=>fetchJSON(u+'?'+new URLSearchParams(ps))));value={errors:{}};r.forEach((v,i)=>{value[specs[i][0]]=v.status==='fulfilled'?v.value:null;if(v.status==='rejected')value.errors[specs[i][0]]='Unavailable'});}if(token!==version.current)return;setPlace({...value,name,retrieved:new Date().toISOString()});setStatus(Object.keys(value.errors||{}).length?'Some providers are unavailable; available results are shown.':'Location updated.')}catch(e){if(token===version.current)setStatus(e.message)}finally{if(token===version.current)setBusy(false)}
 }
 function gps(){if(!navigator.geolocation){setStatus('GPS is not supported in this browser.');return}setStatus('Requesting your location…');navigator.geolocation.getCurrentPosition(p=>load(p.coords.latitude,p.coords.longitude,'Your location'),()=>setStatus('Location permission denied or GPS unavailable. Enter coordinates instead.'),{timeout:15000,maximumAge:60000})}
 const d=place?.weather?.daily,fd=place?.flood?.daily;
 return <><Panel title="Explore a location" note="Search within Sri Lanka or switch to the global map. Click the map to select coordinates."><div className="explorer-controls"><label><input type="checkbox" checked={global} onChange={e=>setGlobal(e.target.checked)}/> Global view</label><label>Place name<input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')search()}} placeholder={global?'Search a city worldwide':'Search Sri Lanka'}/></label><button className="button" disabled={busy} onClick={search}>Search</button><button className="button" onClick={gps} disabled={busy}>Use my GPS</button></div><div className="search-results">{results.map(p=><button className="chip" key={p.id} disabled={busy} onClick={()=>load(p.latitude,p.longitude,`${p.name}, ${p.country}`)}>{p.name} · {p.admin1} · {p.country}</button>)}</div><div className="explorer-controls"><label>Latitude<input type="number" step="any" min="-90" max="90" value={lat} onChange={e=>setLat(e.target.value)}/></label><label>Longitude<input type="number" step="any" min="-180" max="180" value={lon} onChange={e=>setLon(e.target.value)}/></label><button className="button" disabled={busy} onClick={()=>load()}>Load location</button></div><p role="status">{status}</p><div ref={ref} className="global-map" aria-label="Interactive world map"/></Panel>
 {place&&<Panel title={place.name} note={`Retrieved ${place.retrieved}. Forecast days use UTC.`}><div className="stats"><div><strong>{f(place.weather?.current?.temperature_2m)} °C</strong><p>Current modelled temperature</p></div><div><strong>{f(place.elevation?.elevation?.[0])} m</strong><p>Terrain elevation · 90 m DEM</p></div><div><strong>{f(place.weather?.current?.relative_humidity_2m)}%</strong><p>Current humidity</p></div><div><strong>{f(place.weather?.current?.wind_speed_10m)} km/h</strong><p>Current wind</p></div></div><Table heads={['UTC date','Rain mm','Min / max °C','Max wind km/h','Median flow m³/s','Flow P25–P75']} rows={(d?.time||fd?.time||[]).map((date,i)=>{const fi=fd?.time?.indexOf(date)??-1;return [date,f(d?.precipitation_sum?.[i]),`${f(d?.temperature_2m_min?.[i])} / ${f(d?.temperature_2m_max?.[i])}`,f(d?.wind_speed_10m_max?.[i]),f(fd?.river_discharge_median?.[fi]),`${f(fd?.river_discharge_p25?.[fi])}–${f(fd?.river_discharge_p75?.[fi])}`]})}/><p className="small-note">River output represents a nearby model grid and may select a different channel. Elevation alone does not measure flood vulnerability. Forecast ensemble percentiles are not return-period thresholds.</p></Panel>}</>;
}
