import React,{useState,useEffect,useRef} from 'react';
import {f,Panel,Table} from '../components/analysis-charts.jsx';
import {fetchJSON} from '../lib/api.js';
import {forecastSignals,sum} from '../lib/analytics.js';
const normalise=value=>String(value??'').toLowerCase().replace(/\bdistrict\b/g,'').replace(/[^a-z0-9]+/g,' ').trim();
function sriLankanPlace(place){const code=String(place?.meta?.countryCode??'').toUpperCase();const lat=Number(place?.meta?.latitude),lon=Number(place?.meta?.longitude);return code==='LK'||(lat>=5.8&&lat<=10.1&&lon>=79.4&&lon<=82.2)}
function districtReference(place,summary){if(!sriLankanPlace(place)||!summary?.locations?.length)return null;const district=normalise(place.meta?.admin2||place.meta?.admin1);const exact=district&&summary.locations.find(l=>normalise(l.district)===district);if(exact)return exact;const lat=Number(place.meta?.latitude),lon=Number(place.meta?.longitude);return summary.locations.reduce((best,current)=>{const distance=(current.lat-lat)**2+(current.lon-lon)**2;return !best||distance<best.distance?{location:current,distance}:best},null)?.location||null}
function signalText(level){return level===2?'High signal':level===1?'Watch':level===0?'Typical':'Not assessed'}
function signalBadge(level){return <span className={`badge ${level===2?'high':level===1?'elevated':level===0?'typical':'none'}`}>{signalText(level)}</span>}
export function GlobalExplorer({summary,baselines,selectedLocationId,onPlaceChange}){
 const [query,setQuery]=useState(''),[lat,setLat]=useState('6.927'),[lon,setLon]=useState('79.861'),[results,setResults]=useState([]),[status,setStatus]=useState(''),[place,setPlace]=useState(null),[global,setGlobal]=useState(true),[busy,setBusy]=useState(false);
 const ref=useRef(null),mapRef=useRef(null),markerRef=useRef(null),version=useRef(0),previousSelected=useRef(selectedLocationId);
 useEffect(()=>{onPlaceChange?.(place)},[place,onPlaceChange]);
 useEffect(()=>{if(previousSelected.current===selectedLocationId)return;previousSelected.current=selectedLocationId;version.current++;setPlace(null)},[selectedLocationId]);
 useEffect(()=>{if(!window.L)return;const L=window.L,m=L.map(ref.current,{scrollWheelZoom:false}).setView([7.85,80.7],7);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(m);m.on('click',e=>{setLat(e.latlng.lat.toFixed(5));setLon(e.latlng.lng.toFixed(5));setStatus('Coordinates selected. Choose “Load location” to retrieve the forecast.');});mapRef.current=m;return()=>{version.current++;m.remove();mapRef.current=null}},[]);
 useEffect(()=>{mapRef.current?.setView(global?[15,20]:[7.85,80.7],global?2:7)},[global]);
 async function search(){if(query.trim().length<2){setStatus('Enter at least two characters.');return}setBusy(true);setStatus('Searching…');try{const j=await fetchJSON('https://geocoding-api.open-meteo.com/v1/search?'+new URLSearchParams({name:query,count:12,language:'en',format:'json',...(!global?{countryCode:'LK'}:{})}));setResults((j.results||[]).filter(x=>global||x.country_code==='LK'));setStatus((j.results||[]).filter(x=>global||x.country_code==='LK').length?'Select a search result.':'No places found. Try a nearby town.')}catch(e){setStatus(e.message)}finally{setBusy(false)}}
 async function load(a=lat,b=lon,name='Selected coordinates',meta={}){
  const latitude=Number(a),longitude=Number(b);if(String(a).trim()===''||String(b).trim()===''||!Number.isFinite(latitude)||!Number.isFinite(longitude)||Math.abs(latitude)>90||Math.abs(longitude)>180){setStatus('Enter valid latitude (−90 to 90) and longitude (−180 to 180).');return}
  const token=++version.current;setBusy(true);setPlace(null);setStatus('Retrieving weather, river flow and elevation…');setLat(String(latitude));setLon(String(longitude));
  if(mapRef.current){mapRef.current.setView([latitude,longitude],9);markerRef.current?.remove();markerRef.current=window.L.marker([latitude,longitude]).addTo(mapRef.current)}
  try{let value;const p={latitude,longitude};{const specs=[['weather','https://api.open-meteo.com/v1/forecast',{...p,current:'temperature_2m,relative_humidity_2m,wind_speed_10m,pressure_msl',daily:'precipitation_sum,temperature_2m_max,temperature_2m_min,wind_speed_10m_max',forecast_days:16,timezone:'GMT'}],['flood','https://flood-api.open-meteo.com/v1/flood',{...p,daily:'river_discharge_median,river_discharge_p25,river_discharge_p75',models:'forecast_v4',forecast_days:16}],['elevation','https://api.open-meteo.com/v1/elevation',p]];const r=await Promise.allSettled(specs.map(([,u,ps])=>fetchJSON(u+'?'+new URLSearchParams(ps))));value={errors:{}};r.forEach((v,i)=>{value[specs[i][0]]=v.status==='fulfilled'?v.value:null;if(v.status==='rejected')value.errors[specs[i][0]]='Unavailable'});}if(token!==version.current)return;setPlace({...value,name,retrieved:new Date().toISOString(),meta:{...meta,latitude,longitude}});setStatus(Object.keys(value.errors||{}).length?'Some providers are unavailable; available results are shown.':'Location updated.')}catch(e){if(token===version.current)setStatus(e.message)}finally{if(token===version.current)setBusy(false)}
 }
 function gps(){if(!navigator.geolocation){setStatus('GPS is not supported in this browser.');return}setStatus('Requesting your location…');navigator.geolocation.getCurrentPosition(p=>load(p.coords.latitude,p.coords.longitude,'Your location'),()=>setStatus('Location permission denied or GPS unavailable. Enter coordinates instead.'),{timeout:15000,maximumAge:60000})}
 const d=place?.weather?.daily,fd=place?.flood?.daily,reference=place&&districtReference(place,summary),signals=place?forecastSignals(place.weather,place.flood,reference?baselines?.[reference.id]:null):[],maxLevel=signals.length?Math.max(...signals.map(x=>x.level)):-1,retrievedLabel=place?new Date(place.retrieved).toLocaleString('en-GB',{timeZone:'Asia/Colombo'}):'',rainTotal=sum(d?.precipitation_sum||[]),dates=[...new Set([...(d?.time||[]),...(fd?.time||[])])].sort();
 return <><Panel title="Global weather & river explorer" note="Search any place worldwide, use your GPS, or click the map to load a 16-day weather, river-flow and elevation forecast."><div className="explorer-controls"><label><input type="checkbox" checked={global} onChange={e=>setGlobal(e.target.checked)}/> Global view</label><label>Place name<input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')search()}} placeholder={global?'Search a city worldwide':'Search Sri Lanka'}/></label><button className="button" disabled={busy} onClick={search}>Search</button><button className="button" onClick={gps} disabled={busy}>Use my GPS</button></div><div className="search-results">{results.map(p=><button className="chip" key={p.id} disabled={busy} onClick={()=>load(p.latitude,p.longitude,[p.name,p.country].filter(Boolean).join(', '),{countryCode:p.country_code,admin1:p.admin1,admin2:p.admin2})}>{p.name}{p.admin1?` · ${p.admin1}`:''}{p.country?` · ${p.country}`:''}</button>)}</div><div className="explorer-controls"><label>Latitude<input type="number" step="any" min="-90" max="90" value={lat} onChange={e=>setLat(e.target.value)}/></label><label>Longitude<input type="number" step="any" min="-180" max="180" value={lon} onChange={e=>setLon(e.target.value)}/></label><button className="button" disabled={busy} onClick={()=>load()}>Load location</button></div><p role="status">{status}</p><div ref={ref} className="global-map" aria-label="Interactive world map"/></Panel>
 {place&&<Panel title={place.name} note={`Recently retrieved forecast · retrieved ${retrievedLabel} Sri Lanka time · Daily comparisons use UTC dates`}><div className="stats"><div><strong>{f(place.weather?.current?.temperature_2m)} °C</strong><p>Current modelled temperature</p></div><div><strong>{f(place.elevation?.elevation?.[0])} m</strong><p>Terrain elevation · 90 m DEM</p></div><div><strong>{f(place.weather?.current?.relative_humidity_2m)}%</strong><p>Current humidity</p></div><div><strong>{f(place.weather?.current?.wind_speed_10m)} km/h</strong><p>Current wind · pressure {f(place.weather?.current?.pressure_msl)} hPa</p></div><div><strong>{f(rainTotal)} mm</strong><p>16-day forecast total · not observed</p></div></div><div className="outlook-callout"><div><div className="eyebrow">{place.name} · UPCOMING CONDITIONS</div><h2>{reference?(maxLevel===2?'Unusual rainfall or river flow is forecast':maxLevel===1?'Some forecast values are elevated':maxLevel===0?'No elevated signals in the available forecast':'Refresh to assess upcoming conditions'):'Forecast loaded · district comparison unavailable'}</h2><p>{reference?`${signals.filter(r=>r.level>=1).length} of ${signals.length} forecast days exceed the ${reference.district} district reference threshold. Rainfall and modelled river flow are assessed separately. This is a research indicator, not a flood probability.`:'This place is outside the Sri Lankan reference network, so unusual/watch labels are not calculated. The provider forecast remains available.'}</p></div>{reference?signalBadge(maxLevel):<span className="badge none">Global forecast</span>}</div><Table heads={['UTC date','Rain mm','Min / max °C','Max wind km/h','Median flow m³/s','Flow P25–P75','District signal']} rows={dates.map(date=>{const wi=d?.time?.indexOf(date)??-1,fi=fd?.time?.indexOf(date)??-1,signal=signals.find(r=>r.date===date);return [date,f(d?.precipitation_sum?.[wi]),`${f(d?.temperature_2m_min?.[wi])} / ${f(d?.temperature_2m_max?.[wi])}`,f(d?.wind_speed_10m_max?.[wi]),f(fd?.river_discharge_median?.[fi]),`${f(fd?.river_discharge_p25?.[fi])}–${f(fd?.river_discharge_p75?.[fi])}`,reference?signalBadge(signal?.level??-1):<span className="small-note">Not assessed</span>]})}/><p className="small-note">{reference?`Compared with ${reference.district} district values using the ${reference.name} reference location. `:''}River output represents a nearby model grid and may select a different channel. Elevation alone does not measure flood vulnerability. Forecast ensemble percentiles are not return-period thresholds.</p></Panel>}</>;
}
