import {fetchJSON} from './lib/api.js';
import {chart} from './components/time-series.js';
import {pageGuides} from './lib/page-guides.js';
import {mountView} from './views.jsx';
import {finite,sum,mean,maximum,fmt,ordinal,esc,dateLabel,severity,rankReason,monthly,episodes,forecastSignals,snapshotFresh} from './lib/analytics.js';
const $=id=>document.getElementById(id);
const routes=[['overview','Overview','grid'],['weather','Current & forecast','cloud'],['history','Historical explorer','chart'],['flood','Flood indicators','water'],['events','Event replay','play'],['analysis','Exploratory analysis','chart'],['quality','Data & project','database']];
const icons={grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',cloud:'M7 18a5 5 0 1 1 1-10 6 6 0 0 1 11 4 3 3 0 0 1-1 6H7',chart:'M3 3v18h18 M6 15l4-5 4 3 6-8',water:'M2 8q3-3 6 0t6 0t6 0 M2 14q3-3 6 0t6 0t6 0 M2 20q3-3 6 0t6 0t6 0',play:'M8 5l11 7-11 7z',model:'M4 8h16v12H4z M8 8V4h8v4 M8 12v3 M16 12v3 M9 18h6',database:'M3 5c0-4 18-4 18 0s-18 4-18 0v14c0 4 18 4 18 0V5 M3 12c0 4 18 4 18 0'};
const titles={analysis:['Exploratory analysis','Distributions, correlations, monsoon comparisons and unusual conditions across all 25 districts.'],overview:['Sri Lanka weather & flood overview','Explore historical conditions on the map, then check the API forecast for what comes next.'],weather:['Current weather & 16-day forecast','Search any place worldwide, then compare its provider forecast with the selected Sri Lankan monitoring location.'],history:['Historical weather explorer','Explore historical weather, seasonality and differences across locations.'],flood:['Flood indicators & priority locations','Compare modelled discharge, accumulated rainfall and seasonal baselines.'],events:['Extreme weather events','Replay automatically identified episodes, one day at a time.'],quality:['Data, methods & project guide','Data coverage, reproducibility, methodology and team handover.']};
const colors=['#258d7d','#c48a22','#c95645'];
let state={route:'overview',loc:'hanwella',start:'2026-06-01',end:'2026-09-07',mapMode:'history',metric:'rain',eventIndex:0,eventDay:0,eventKind:'flood',live:null,liveError:'',playing:false,explorerPlace:null};
let summary,geo,baselines,lags,data={},playTimer,renderToken=0;
const loc=()=>summary.locations.find(x=>x.id===state.loc)||summary.locations[0];
const allRows=(id=state.loc)=>data[id]||[];
const rows=(id=state.loc)=>allRows(id).filter(x=>x.date>=state.start&&x.date<=state.end);
const icon=k=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round" stroke-linecap="round" aria-hidden="true"><path d="${icons[k]||icons.grid}"/></svg>`;
function badge(n){return `<span class="badge ${n===2?'high':n===1?'elevated':n===0?'typical':'none'}">${n===2?'Unusual':n===1?'Elevated':n===0?'Typical':'No data'}</span>`;}
function stat(label,value,unit,meta,symbol='↗'){return `<article class="stat"><div class="stat-label">${label}<span class="stat-symbol" aria-hidden="true">${symbol}</span></div><div class="stat-value">${value}<small>${unit}</small></div><div class="stat-meta">${meta}</div></article>`;}
function card(title,subtitle,body,extra=''){return `<section class="card"><div class="card-head"><div><h2>${title}</h2>${subtitle?`<p>${subtitle}</p>`:''}</div>${extra}</div>${body}</section>`;}
function empty(title,text){return `<div class="empty"><h2>${title}</h2><p>${text}</p></div>`;}
function notice(text){$('notice').hidden=!text;$('notice').textContent=text;}

const points=(a,key)=>a.map(r=>({d:r.date,v:r[key]}));
let activeMap=null;
function forecastRows(id=state.loc){return forecastSignals(state.live?.weather?.[id],state.live?.flood?.[id],baselines[id],{weatherFresh:snapshotFresh(state.live?.weather_at?.[id]||state.live?.retrieved_at),floodFresh:snapshotFresh(state.live?.flood_at?.[id]||state.live?.retrieved_at)}).filter(r=>r.date>=new Date().toISOString().slice(0,10));}
function forecastLevel(id){const r=forecastRows(id);return r.length?Math.max(...r.map(x=>x.level)):-1;}
function riskBadge(level){return `<span class="badge ${level===2?'high':level===1?'elevated':level===0?'typical':'none'}">${level===2?'High signal':level===1?'Watch':level===0?'No elevated signal':'Unavailable'}</span>`;}
function map(selectedDate=state.end){
 const px=lon=>80+(lon-79.4)*140*Math.cos(7.8*Math.PI/180),py=lat=>30+(10.05-lat)*140;
 const polygons=geo.features.flatMap(f=>f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates);
 const paths=polygons.map(rings=>`<path d="${rings.map(r=>'M'+r.map(([lon,lat])=>`${px(lon).toFixed(2)},${py(lat).toFixed(2)}`).join('L')+'Z').join('')}"/>`).join('');
 const dots=summary.locations.map(l=>`<circle class="map-dot" tabindex="0" role="button" data-location="${l.id}" aria-label="Select ${esc(l.name)}" cx="${px(l.lon)}" cy="${py(l.lat)}" r="5" fill="${colors[state.mapMode==='forecast'?forecastLevel(l.id):((allRows(l.id).find(x=>x.date===selectedDate)?.severity)??-1)]||'#8c9da8'}"><title>${esc(l.name)}</title></circle>`).join('');
 return `<div class="map-toolbar"><div class="metric-tabs"><button class="chip ${state.mapMode==='history'?'active':''}" data-map-mode="history">Historical · ${dateLabel(selectedDate)}</button><button class="chip ${state.mapMode==='forecast'?'active':''}" data-map-mode="forecast">Next 16 days</button></div><button id="map-reset" class="text-button">Reset map</button></div><div id="sri-lanka-map" class="geographic-map" aria-label="Interactive geographic map of Sri Lanka"><svg class="geographic-fallback" viewBox="0 0 480 650" role="img" aria-label="Sri Lanka geographic district boundaries and monitoring points"><g fill="#edf3ed" stroke="#85a3ac" stroke-width=".65">${paths}</g>${dots}</svg></div><div class="map-legend"><span><i style="background:${colors[0]}"></i>${state.mapMode==='forecast'?'No elevated signal':'Typical'}</span><span><i style="background:${colors[1]}"></i>${state.mapMode==='forecast'?'Watch':'Elevated'} ≥95th</span><span><i style="background:${colors[2]}"></i>${state.mapMode==='forecast'?'High signal':'Unusual'} ≥99th</span><span><i style="background:#8c9da8"></i>No data</span></div><p class="map-note">Zoom and click a point. Boundaries show 25 districts; colours describe sampled locations, not flooded areas. <a href="https://www.geoboundaries.org" target="_blank" rel="noreferrer">geoBoundaries</a> / © OpenStreetMap contributors.</p>`;
}
function mountMap(){
 if(!$('sri-lanka-map')||!globalThis.L)return;
 const L=globalThis.L;
 $('sri-lanka-map').innerHTML='';
 activeMap=L.map('sri-lanka-map',{scrollWheelZoom:false,attributionControl:true}).setView([7.85,80.7],7);
 const tile=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(activeMap);
 tile.on('tileerror',()=>{$('map-status')?.remove();});
 const boundaries=L.geoJSON(geo,{style:{color:'#4b7985',weight:1,fillColor:'#e7f0e8',fillOpacity:.15},onEachFeature:(feature,layer)=>layer.bindTooltip(esc(feature.properties.shapeName),{sticky:true})}).addTo(activeMap);
 activeMap.fitBounds(boundaries.getBounds(),{padding:[18,18]});
 L.control.scale({imperial:false}).addTo(activeMap);
 summary.locations.forEach(l=>{
  const row=allRows(l.id).find(r=>r.date===state.end),level=state.mapMode==='forecast'?forecastLevel(l.id):row?.severity??-1;
  const marker=L.circleMarker([l.lat,l.lon],{radius:l.id===state.loc?9:6,color:l.id===state.loc?'#123d59':'#fff',weight:l.id===state.loc?3:1.5,fillColor:colors[level]||'#8c9da8',fillOpacity:1}).addTo(activeMap);
  const text=state.mapMode==='forecast'?`API outlook · ${forecastRows(l.id).filter(r=>r.level>=1).length} elevated days`:`${dateLabel(state.end)} · ${rankReason(row)[0]}`;
  marker.bindTooltip(`<strong>${esc(l.name)}</strong><br>${esc(text)}`,{direction:'top'});
  marker.on('click',()=>selectLocation(l.id));
 });
 $('map-reset')?.addEventListener('click',()=>activeMap.fitBounds(boundaries.getBounds(),{padding:[18,18]}));
}
function overview(){
 const a=rows(),last=a.at(-1),reason=rankReason(last);const ranking=summary.locations.map(l=>({l,r:allRows(l.id).find(x=>x.date===state.end)})).sort((x,y)=>(rankReason(y.r)[1]??-1)-(rankReason(x.r)[1]??-1));
 const unusual=ranking.filter(x=>x.r?.severity===2).length;
 const monthlyRain=monthly(a,'rain');
 return `<div class="stats">${stat('Monitored locations',String(summary.locations.length),'locations',`${summary.locations.filter(x=>x.valid_q>0).length} include river-discharge data`,'⌖')}${stat('Unusual conditions',String(unusual),'locations',`At or above local 99th percentile · ${dateLabel(state.end)}`,'◈')}${stat('Selected rainfall',fmt(sum(a.map(r=>r.rain))),'mm',`${esc(loc().name)} · selected date range`,'☂')}${stat('Latest river discharge',fmt(last?.q),'m³/s',`${dateLabel(last?.date)} · modelled daily flow`,'≈')}</div>
 <div class="workspace-grid">${card('Sri Lanka at a glance','A point-based view of weather and river signals',map(),`<span class="badge none">${summary.locations.length} monitoring points</span>`)}${card('Locations to explore',`Highest seasonal percentile on ${dateLabel(state.end)}`,`<div class="location-list">${ranking.slice(0,6).map(({l,r},i)=>`<button class="location-row" data-location="${l.id}"><span class="rank">${String(i+1).padStart(2,'0')}</span><span><span class="location-name">${esc(l.name)}</span><span class="location-region" style="display:block">${esc(rankReason(r)[0])} · ${ordinal(rankReason(r)[1])} percentile</span></span>${badge(r?.severity??-1)}</button>`).join('')}</div><div class="info-strip">Each location is compared with its own ${esc(summary.baseline_period)} monthly baseline. A high percentile signals unusual conditions, not a confirmed flood.</div>`)}</div>
 <div class="bottom-grid">${card(`${esc(loc().name)} · rainfall`,`Monthly totals within your selected dates`,`<div class="card-body">${chart([{name:'Rainfall',points:monthlyRain.map(x=>({d:x.date,v:x.value}))}],{unit:'mm',bars:false})}</div>`)}${card('The signal behind the status',`${esc(loc().name)} · ${dateLabel(last?.date)}`,`<div class="card-body"><div class="insight"><strong>${esc(reason[0].charAt(0).toUpperCase()+reason[0].slice(1))}</strong> is at the <strong>${ordinal(reason[1])} seasonal percentile</strong>. ${finite(reason[1])&&reason[1]>=95?'This is an elevated historical indicator worth examining in context.':'The selected day does not show an elevated value for this leading indicator.'}</div><div class="bar-list">${[['3-day rainfall',last?.rp],['River discharge',last?.qp],['Temperature',last?.tp],['Wind speed',last?.wp]].map(([n,v])=>`<div class="bar-item"><span>${n}</span><div class="bar-track"><div class="bar-fill" style="width:${v??0}%"></div></div><span>${ordinal(v)}</span></div>`).join('')}</div><button class="text-button section-space" data-route="flood">Explore flood indicators →</button></div>`)}</div>`;
}
function history(){
 const a=rows();const metric={rain:['Rainfall','mm'],temp:['Mean temperature','°C'],humidity:['Relative humidity','%'],wind:['Maximum wind speed','km/h'],pressure:['Mean sea-level pressure','hPa']}[state.metric];
 const monthlyData=monthly(a,state.metric);const seasonal=Array.from({length:12},(_,m)=>{const b=allRows().filter(r=>Number(r.date.slice(5,7))===m+1);return {d:new Date(Date.UTC(Number(summary.start.slice(0,4)),m,1)).toLocaleString('en',{month:'short',timeZone:'UTC'}),v:mean(b.map(r=>r[state.metric]))};});
 const compare=summary.locations.map(l=>{const b=rows(l.id);return {l,avg:mean(b.map(r=>r[state.metric])),total:sum(b.map(r=>r.rain)),peak:maximum(b.map(r=>r[state.metric])),n:b.filter(r=>finite(r[state.metric])).length};}).sort((x,y)=>(y.avg??-Infinity)-(x.avg??-Infinity));
 return `<div class="stats">${stat('Valid daily records',fmt(a.filter(r=>finite(r[state.metric])).length,0),'days',esc(loc().name))}${stat('Daily average',fmt(mean(a.map(r=>r[state.metric]))),metric[1],metric[0])}${stat('Daily maximum',fmt(maximum(a.map(r=>r[state.metric]))),metric[1],'Within selected date range')}${stat('Rainfall total',fmt(sum(a.map(r=>r.rain))),'mm','Sum of complete UTC days')}</div>
 ${card(`${esc(loc().name)} · ${metric[0].toLowerCase()}`,'Select a weather indicator to explore',`<div class="metric-tabs">${[['rain','Rainfall'],['temp','Temperature'],['humidity','Humidity'],['wind','Wind'],['pressure','Pressure']].map(([k,n])=>`<button class="chip ${state.metric===k?'active':''}" data-metric="${k}">${n}</button>`).join('')}</div><div class="card-body">${chart([{name:metric[0],points:points(a,state.metric)}],{unit:metric[1],height:255})}<p class="small-note">Daily summaries; rainfall is summed, wind uses the daily maximum, and other selected indicators use the daily mean.</p></div>`)}
 <div class="two-grid">${card('Monthly comparison','Totals for rainfall; mean of daily summaries for other indicators',`<div class="card-body">${chart([{name:metric[0],points:monthlyData.map(x=>({d:x.date,v:x.value}))}],{unit:metric[1],bars:false})}</div>`)}${card('Seasonal baseline','${esc(summary.baseline_period)} · average daily value for each calendar month',`<div class="card-body">${chart([{name:'Historical monthly baseline',points:seasonal}],{unit:metric[1],bars:false})}</div>`)}</div>
 <div class="section-space">${card('Compare monitoring locations',`Ranked by mean daily ${metric[0].toLowerCase()} in your date range`,`<div class="table-wrap"><table><thead><tr><th>Location</th><th>Region</th><th>Daily average (${metric[1]})</th><th>Daily maximum</th><th>Valid days</th></tr></thead><tbody>${compare.map(({l,avg,peak,n})=>`<tr><td><button class="table-button" data-location="${l.id}">${esc(l.name)}</button></td><td>${esc(l.region)}</td><td>${fmt(avg)}</td><td>${fmt(peak)}</td><td>${n}</td></tr>`).join('')}</tbody></table></div>`)}</div>`;
}
function flood(){
 if(!loc().river)return empty('Choose a river monitoring location',`${esc(loc().name)} is a weather-only point. Choose Hanwella, Ratnapura or another river point to explore modelled discharge.`);
 const a=rows(),last=a.at(-1),floodRows=a.filter(x=>finite(x.q));if(!floodRows.length)return empty('No river data in this selection','Choose another date range or river monitoring location.');
 const ls=lags[state.loc]||[];const best=[...ls].filter(x=>finite(x.r)).sort((a,b)=>b.r-a.r)[0];const ep=episodes(a.filter(r=>true));const th=a.map(r=>({d:r.date,v:baselines[state.loc].q[String(Number(r.date.slice(5,7)))]?.p95}));
 return `<div class="stats">${stat('Latest discharge',fmt(last?.q),'m³/s',dateLabel(last?.date),'≈')}${stat('Peak discharge',fmt(maximum(a.map(r=>r.q))),'m³/s','Selected period','↗')}${stat('Unusual episodes',String(ep.length),'episodes','Rainfall or discharge ≥99th percentile','◈')}${stat('Strongest tested lag',best?String(best.lag):'—','days',best?`Deseasonalised Pearson r = ${fmt(best.r,2)}`:'Insufficient variation','⇄')}</div>
 ${card(`${esc(loc().name)} · river discharge`,'Daily modelled flow against its ${esc(summary.baseline_period)} monthly 95th-percentile baseline',`<div class="card-body">${chart([{name:'GloFAS discharge',points:points(a,'q')},{name:'Monthly 95th percentile',points:th,color:'#d09640',dashed:true}],{unit:'m³/s',height:265})}<div class="insight">${esc(loc().river)} · the API returned grid <strong>${loc().flood_grid.map(x=>fmt(x,3)).join(', ')}</strong>. The named river is a geographic reference; the selected channel has not been independently verified.</div></div>`)}
 <div class="two-grid">${card('Rainfall accumulation','Rainfall at this weather grid, not an upstream catchment average',`<div class="card-body">${chart([{name:'3-day total',points:points(a,'r3')},{name:'7-day total',points:points(a,'r7'),color:'#638bc4'}],{unit:'mm'})}</div>`)}${card('Rainfall–discharge lag','Full archive · seasonal monthly means removed',`<div class="card-body">${chart([{name:'Pearson correlation',points:ls.map(x=>({d:`${x.lag} days`,v:x.r}))}],{unit:'r',bars:false})}<p class="small-note">Positive lag means earlier local rainfall is compared with later discharge. Association is exploratory; autocorrelation and upstream rainfall can affect it.</p></div>`)}</div>
 <div class="section-space">${card('Flood-related episodes in your selection','Episodes from 2016 onward in your selection; discharge or 3-day rain at or above the 99th percentile',`<div class="table-wrap"><table><thead><tr><th>Start</th><th>End</th><th>Duration</th><th>Peak day</th><th></th></tr></thead><tbody>${ep.slice(0,12).map(e=>`<tr><td>${dateLabel(e.start)}</td><td>${dateLabel(e.end)}</td><td>${e.days} days</td><td>${dateLabel(e.peakDate)}</td><td><button class="table-button" data-replay-date="${e.peakDate}">Replay →</button></td></tr>`).join('')||'<tr><td colspan="5">No threshold-exceedance episodes in this selection.</td></tr>'}</tbody></table></div>`)}</div>`;
}
function regionalFloodTable(){
 const ranked=summary.locations.filter(l=>l.river).map(l=>{const a=rows(l.id),valid=a.filter(r=>finite(r.qp)&&finite(r.rp));const unusual=valid.filter(r=>Math.max(r.qp,r.rp)>=99);return {l,n:valid.length,count:unusual.length,rate:valid.length?100*unusual.length/valid.length:null,peak:maximum(a.map(r=>r.q)),both:valid.filter(r=>r.qp>=95&&r.rp>=95).length};}).sort((a,b)=>(b.rate??-1)-(a.rate??-1));
 return card('Which locations deserve closer investigation?','Ranked by the share of selected days with unusual rainfall or flow; these are sampled points within regions',`<div class="table-wrap"><table><thead><tr><th>Location / region</th><th>Unusual days</th><th>Share of valid days</th><th>Rain + flow both elevated</th><th>Peak flow (m³/s)</th></tr></thead><tbody>${ranked.map(x=>`<tr><td><button class="table-button" data-location="${x.l.id}">${esc(x.l.name)}</button><br><span class="small-note">${esc(x.l.region)}</span></td><td>${x.count} / ${x.n}</td><td>${fmt(x.rate,1)}%</td><td>${x.both} days</td><td>${fmt(x.peak)}</td></tr>`).join('')}</tbody></table></div><p class="map-note">High values indicate recurring unusual conditions in the selected data, not measured exposure or guaranteed flood risk. Use the forecast page for upcoming signals.</p>`);
}
function eventCandidates(){return episodes(allRows(),99,state.eventKind);}
function events(){
 const candidates=eventCandidates();if(!candidates.length)return empty('No matching extreme episodes','Try another location. Episodes require valid values above the local seasonal 99th percentile.');
 state.eventIndex=Math.min(state.eventIndex,candidates.length-1);const ev=candidates[state.eventIndex];const full=allRows();const peak=full.findIndex(r=>r.date===ev.peakDate);const start=Math.max(0,peak-7),end=Math.min(full.length-1,Math.max(peak+7,full.findIndex(r=>r.date===ev.end)+3));const segment=full.slice(start,end+1);state.eventDay=Math.min(state.eventDay,segment.length-1);const r=segment[state.eventDay];const reason=rankReason(r);
 return `<div class="inline-controls"><label for="event-kind" class="small-note">Episode type</label><select id="event-kind">${[['flood','Rainfall & river flow'],['rain','Extreme rainfall'],['heat','Unusual heat'],['wind','Unusual wind']].map(([k,n])=>`<option value="${k}" ${state.eventKind===k?'selected':''}>${n}</option>`).join('')}</select><select id="event-select" aria-label="Select historical episode">${candidates.map((e,i)=>`<option value="${i}" ${state.eventIndex===i?'selected':''}>${dateLabel(e.start)} · ${e.days} day${e.days===1?'':'s'}</option>`).join('')}</select><span class="small-note">Episodes since 2016 · independent of date filters</span></div>
 <div class="replay-layout">${card('Episode timeline',`${esc(loc().name)} · ${dateLabel(segment[0].date)} to ${dateLabel(segment.at(-1).date)}`,`<div class="card-body"><div class="inline-controls"><button id="play-replay" class="button primary">${state.playing?'Ⅱ Pause':'▷ Play'}</button><input id="replay-range" class="replay-range" type="range" min="0" max="${segment.length-1}" value="${state.eventDay}" aria-label="Replay day"><span class="small-note">Day ${state.eventDay+1}/${segment.length}</span></div>${chart([{name:state.eventKind==='heat'?'Maximum temperature':state.eventKind==='wind'?'Maximum wind':state.eventKind==='rain'||!loc().valid_q?'3-day rainfall':'River discharge',points:points(segment.slice(0,state.eventDay+1),state.eventKind==='heat'?'tmax':state.eventKind==='wind'?'wind':state.eventKind==='rain'||!loc().valid_q?'r3':'q')}],{unit:state.eventKind==='heat'?'°C':state.eventKind==='wind'?'km/h':state.eventKind==='rain'||!loc().valid_q?'mm':'m³/s'})}${chart([{name:'Daily rainfall',points:points(segment.slice(0,state.eventDay+1),'rain')}],{unit:'mm',bars:false,height:185})}</div>`)}<section class="card replay-story"><div class="eyebrow">${esc(loc().name)} · HISTORICAL REPLAY</div><div class="replay-date">${dateLabel(r.date)}</div><div style="margin-top:15px">${badge(r.severity)}</div><h2>${reason[1]>=99?'An unusual signal emerges.':reason[1]>=95?'Conditions are elevated.':'A quieter point in the episode.'}</h2><p>${esc(reason[0].charAt(0).toUpperCase()+reason[0].slice(1))} reaches the ${ordinal(reason[1])} percentile for this calendar month. Follow the days to see how local rainfall and modelled river flow evolve.</p><div class="replay-stats"><div>Daily rainfall<strong>${fmt(r.rain)} <small>mm</small></strong></div><div>3-day rainfall<strong>${fmt(r.r3)} <small>mm</small></strong></div><div>River discharge<strong>${fmt(r.q)} <small>m³/s</small></strong></div><div>Maximum temperature<strong>${fmt(r.tmax)} <small>°C</small></strong></div></div><p class="small-note" style="margin-top:20px">This is an algorithmically identified episode in modelled data. It is not independently confirmed as a flood disaster.</p></section></div>`;
}
function quality(){
 return `<div class="stats">${stat('Archive starts',summary.start,'','Completed UTC days')}${stat('Latest historical day',summary.end,'','Latest saved and validated release')}${stat('Daily records',fmt(summary.daily_rows,0),'','25 district reference points')}${stat('Reference period',summary.baseline_period,'','Full-archive retrospective analysis')}</div>
 <div class="two-grid">${card('Data and interpretation','What these indicators mean',`<div class="card-body"><p>One point per district is compared with the same calendar month across the full archive. These are modelled weather and flow values, not district averages or confirmed floods.</p><p>Elevated: at least the 95th percentile. Unusual: at least the 99th. Past classifications can change when the archive grows.</p><p>The latest-day screening index weights flow 50%, three-day rainfall 30% and heat/wind 20%, with available weights rescaled when a component is missing.</p></div>`)}
 ${card('Daily saved updates','GitHub Actions → validated data → Vercel',`<div class="card-body"><p>Scheduled collection saves new completed-day history and forecast snapshots. Live refresh updates this browser; shared saved data updates when the scheduled job publishes successfully.</p><p>Last release: ${esc(summary.generated_at)}. Provider outages may delay updates. Old forecasts retain their original timestamps.</p><p>Missing flow remains unavailable at Trincomalee and Mullaitivu.</p></div>`)}</div>
 ${card('Downloads and reproducibility','Keep data dates and provider timestamps with your analysis',`<div class="card-body sources-list"><a href="data/historical-daily.csv" download>Historical daily CSV</a><a href="data/forecast-daily.csv" download>Saved forecast CSV</a><a href="data/validation.json" download>Validation evidence</a><a href="data/summary.json" download>Coverage and source metadata</a><a href="docs/METHODOLOGY.md" download>Methodology</a><a href="docs/REPORT.md" download>Project report</a></div>`)}
 <p class="small-note">Group A · Kasun Vishvajith · Akindu Liyanage · Yasuri Fernando. API forecasts only; no project-trained forecasting model. River channel identity and actual flood events have not been independently validated.</p>`;
}

function weather(){
 const w=state.live?.weather?.[state.loc],f=state.live?.flood?.[state.loc],c=w?.current,d=w?.daily;
 const stamp=state.live?.weather_at?.[state.loc]||state.live?.retrieved_at,fs=state.live?.flood_at?.[state.loc]||state.live?.retrieved_at;
 const fresh=snapshotFresh(stamp),flowFresh=snapshotFresh(fs);
 let body='';
 if(state.explorerPlace)return '';
 if(!d)return empty('Forecast unavailable','Use Refresh weather to request the latest API forecast. Historical analysis remains available.');
 const signals=forecastRows(),maxLevel=signals.length?Math.max(...signals.map(r=>r.level)):-1;
 body+=`<div class="source-banner ${fresh?'':'stale'}"><span><strong>${fresh?'Recently retrieved forecast':'Stale forecast — refresh before interpreting'}</strong> · retrieved ${esc(new Date(stamp).toLocaleString('en-GB',{timeZone:'Asia/Colombo'}))} Sri Lanka time</span><span>Daily comparisons use UTC dates</span></div>${state.liveError?`<p class="notice">${esc(state.liveError)}</p>`:''}
 <div class="stats">${stat(fresh?'Current temperature':'Saved temperature',fmt(c?.temperature_2m),'°C',`${esc(loc().name)} · modelled conditions`,'☀')}${stat(fresh?'Current humidity':'Saved humidity',fmt(c?.relative_humidity_2m,0),'%','Relative humidity','◌')}${stat(fresh?'Current wind':'Saved wind',fmt(c?.wind_speed_10m),'km/h',`Sea-level pressure ${fmt(c?.pressure_msl)} hPa`,'≋')}${stat('Forecast rainfall',d.precipitation_sum?.some(finite)?fmt(sum(d.precipitation_sum)):'—','mm',`${d.time.length}-day forecast total · not observed`,'☂')}</div>
 <div class="outlook-callout"><div><div class="eyebrow">${esc(loc().name)} · UPCOMING CONDITIONS</div><h2>${maxLevel===2?'Unusual rainfall or river flow is forecast':maxLevel===1?'Some forecast values are elevated':maxLevel===0?'No elevated signals in the available forecast':'Refresh to assess upcoming conditions'}</h2><p>${signals.filter(r=>r.level>=1).length} of ${signals.length} forecast days exceed a historical threshold. ${!loc().river?'This point has weather indicators only.':'Rainfall and modelled river flow are assessed separately.'} This is a research indicator, not a flood probability.</p></div>${riskBadge(maxLevel)}</div>
 ${card(`${esc(loc().name)} · saved forecast days`,'Predictions supplied by Open-Meteo; no project-trained model',`<div class="card-body"><div class="forecast-strip">${d.time.map((date,i)=>`<div class="forecast-day"><span>${new Date(date+'T00:00Z').toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short',timeZone:'UTC'})}</span><strong>${fmt(d.temperature_2m_max?.[i],0)}°</strong><span>Low ${fmt(d.temperature_2m_min?.[i],0)}°</span><em>${fmt(d.precipitation_sum?.[i])} mm</em><span>Rain chance ${fmt(d.precipitation_probability_max?.[i],0)}%</span><span>${fmt(d.wind_speed_10m_max?.[i],0)} km/h</span></div>`).join('')}</div><p class="small-note section-space">The first day can be today’s incomplete day. Rain chance comes from the weather API and is not a flood probability.</p></div>`)}
  <div class="two-grid">${card('Forecast rainfall',`Daily rain compared with the ${esc(summary.baseline_period)} monthly 95th percentile`,`<div class="card-body">${chart([{name:'Forecast rainfall',points:signals.map(r=>({d:r.date,v:r.rain}))},{name:'Historical 95th percentile',points:signals.map(r=>({d:r.date,v:r.rainP95})),dashed:true,color:'#c58c2b'}],{unit:'mm'})}</div>`)}${card('River-discharge outlook',loc().river?'GloFAS ensemble median and middle 50% of members':'Weather-only reference point',`<div class="card-body">${f?.daily?chart([{name:'Median forecast',points:signals.map(r=>({d:r.date,v:r.q}))},{name:'25th percentile',points:signals.map(r=>({d:r.date,v:r.p25})),dashed:true,color:'#8dabc7'},{name:'75th percentile',points:signals.map(r=>({d:r.date,v:r.p75})),dashed:true,color:'#c58c2b'}],{unit:'m³/s'}):'<p>No river forecast is available for this location.</p>'}<p class="small-note">${f?.daily?`${flowFresh?'':'Older snapshot · '}retrieved ${esc(new Date(fs).toLocaleString('en-GB',{timeZone:'Asia/Colombo'}))} Sri Lanka time. `:''}Ensemble spread describes variation between model members, not a calibrated confidence interval for flooding.</p></div>`)}</div>
 <div class="section-space">${card('Why each day is flagged','Watch ≥95th percentile; high signal ≥99th. Stale or missing sources are excluded from flags.',`<div class="table-wrap"><table><thead><tr><th>UTC date</th><th>Rain (mm)</th><th>Rain indicator</th><th>Flow (m³/s)</th><th>Flow indicator</th></tr></thead><tbody>${signals.map(r=>`<tr><td>${dateLabel(r.date)}</td><td>${fmt(r.rain)}</td><td>${riskBadge(r.rainLevel)}</td><td>${fmt(r.q)}</td><td>${riskBadge(r.flowLevel)}</td></tr>`).join('')}</tbody></table></div><p class="map-note">Forecast and historical products can differ in grid resolution and bias. These thresholds are exploratory and have not been validated against observed flood events.</p>`)}</div>
 <div class="section-space">${card('Compare upcoming signals across locations','Ranked by the highest available rainfall or flow indicator; stale forecasts are excluded',`<div class="table-wrap"><table><thead><tr><th>Location</th><th>Region</th><th>Outlook</th><th>Elevated days</th><th>Weather retrieved (Sri Lanka)</th></tr></thead><tbody>${summary.locations.map(l=>({l,s:forecastRows(l.id),level:forecastLevel(l.id)})).sort((a,b)=>b.level-a.level).map(({l,s,level})=>`<tr><td><button class="table-button" data-location="${l.id}">${esc(l.name)}</button></td><td>${esc(l.region)}</td><td>${riskBadge(level)}</td><td>${s.filter(r=>r.level>=1).length}</td><td>${esc(new Date(state.live?.weather_at?.[l.id]||state.live?.retrieved_at).toLocaleString('en-GB',{timeZone:'Asia/Colombo'}))}</td></tr>`).join('')}</tbody></table></div>`)}</div>`;
 return body;
}
function render(){
 if(!summary)return;document.body.dataset.view=state.route;const guide=$('page-guide');if(guide)guide.innerHTML=pageGuides[state.route].map(([title,body])=>`<dt>${esc(title)}</dt><dd>${esc(body)}</dd>`).join('');if(activeMap){activeMap.remove();activeMap=null;}renderToken++;$('breadcrumb').textContent=routes.find(r=>r[0]===state.route)?.[1]||'Overview';$('page-title').textContent=titles[state.route][0];$('page-description').textContent=titles[state.route][1];
 const explorerActive=state.route==='weather'&&state.explorerPlace;
 $('navigation').innerHTML=routes.map(([id,name,i])=>`<button class="nav-button ${state.route===id?'active':''}" data-route="${id}" ${state.route===id?'aria-current="page"':''}>${icon(i)}${name}</button>`).join('');
 $('location').value=state.loc;$('archive-status').textContent=`Archive: ${dateLabel(summary.start)} – ${dateLabel(summary.end)} · build ${dateLabel(summary.as_of)}`;$('coverage').textContent=state.route==='weather'?'API forecasts · UTC days':state.route==='analysis'?'Full available archive':state.route==='events'?'Episodes since 2016':`${fmt(rows().length,0)} daily records · UTC`;
 const context=$('global-context');if(context){
   const selected=loc(),independent=state.route==='quality';
  const period=state.route==='weather'?'Provider forecast':state.route==='analysis'?'Full archive':state.route==='events'?'Historical episodes':`${dateLabel(state.start)} – ${dateLabel(state.end)}`;
   context.textContent=independent?'Saved selection · '+selected.district+' / '+selected.name:explorerActive?`${state.explorerPlace.name} · Global provider forecast`:`${selected.district} / ${selected.name} · ${period}`;
   $('filter-scope').textContent=independent?'This selection is saved for the district pages. The project guide covers the whole dataset.':state.route==='weather'?(explorerActive?'The searched place is active above. Sri Lankan places use their matching district reference for unusual-signal comparisons.':'Search any place worldwide above; the selected Sri Lankan location is used until a global forecast is loaded.') :state.route==='analysis'?'Choose a reference location. Analysis always uses the full available archive.':state.route==='events'?'Choose a reference location, then select an episode on this page. The archive date range does not apply.':'Applies to Overview, Historical explorer and Flood indicators. Each district uses one reference location, not a district-wide average.';
 }
 const view=({overview,weather,history,flood,events,quality}[state.route]);mountView($('content'),{route:state.route,html:view?view()+(state.route==='flood'?`<div class="section-space">${regionalFloodTable()}</div>`:''):'',summary,baselines,location:state.loc,onLocation:selectLocation,onExplorerPlace:setExplorerPlace});
 const forecastPage=state.route==='weather',forecastAvailable=explorerActive?!!state.explorerPlace.weather?.daily:!!state.live?.weather?.[state.loc]?.daily;
 const recent=explorerActive?true:snapshotFresh(state.live?.weather_at?.[state.loc]||state.live?.retrieved_at);
  $('data-badge').textContent=forecastPage?(forecastAvailable?(explorerActive?'Global forecast · recently retrieved':recent?'Forecast · recently retrieved':'Stale forecast · refresh needed'):'Forecast unavailable'):'Historical model data';
 $('data-badge').classList.toggle('stale',forecastPage&&!recent);
  $('location-context').hidden=state.route==='quality';
  $('location-context').textContent=explorerActive?`${state.explorerPlace.name} global forecast is active. Sri Lankan district comparison is shown only when a matching reference exists.`:`${loc().district} district · ${loc().name} reference location. One sampled coordinate, not a district average.${loc().valid_q>0?'':' River-flow history is unavailable at this point; weather remains available.'}`;
  const supported=!['quality','events'].includes(state.route);
 $('export').hidden=!supported;$('export-context').hidden=!supported;
 $('export').textContent=forecastPage?(explorerActive?'↓ Export selected forecast CSV':'↓ Export forecast CSV'):'↓ Export history CSV';
 const exportDates=forecastPage?(explorerActive?forecastSignals(state.explorerPlace.weather,state.explorerPlace.flood,null):forecastRows()).map(r=>r.date):(state.route==='analysis'?allRows():rows()).map(r=>r.date);
 $('export').disabled=!exportDates.length;
 const exportDescription=forecastPage?(explorerActive?'global provider forecast':'provider forecast'):'historical weather and flow; not an analysis report';
 $('export-context').textContent=exportDates.length?`CSV: ${explorerActive?state.explorerPlace.name:loc().name} · ${dateLabel(exportDates[0])} – ${dateLabel(exportDates.at(-1))} · ${exportDates.length} daily records · ${exportDescription}. Missing values stay blank.`:'No records to export for this selection.';
 $('export').setAttribute('aria-describedby','export-context');
 $('date-presets').hidden=state.route==='weather'||state.route==='events'||state.route==='quality';
 $('start-date').disabled=state.route==='weather'||state.route==='events'||state.route==='quality';$('end-date').disabled=$('start-date').disabled;$('apply-dates').disabled=$('start-date').disabled;
 bindLocal();mountMap();
}
function navigate(route){if(!titles[route])return;stopReplay();if(route!=='weather')state.explorerPlace=null;state.route=route;location.hash=route;render();}
function setExplorerPlace(place){if(state.explorerPlace===place)return;state.explorerPlace=place;if(state.route==='weather')render();}
let feedbackTimer;
function confirmUpdate(){
 const feedback=$('update-feedback');if(!feedback)return;
 clearTimeout(feedbackTimer);feedback.hidden=false;
 feedback.textContent='Updated · '+$('global-context').textContent;
 $('global-filters').open=false;
 if(!globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches&&$('content').animate)$('content').animate([{opacity:.55},{opacity:1}],{duration:220});
 feedbackTimer=setTimeout(()=>{feedback.hidden=true},5000);
}
function selectLocation(id){if(!summary.locations.some(l=>l.id===id))return;stopReplay();state.loc=id;state.explorerPlace=null;state.eventIndex=0;state.eventDay=0;render();confirmUpdate();}
function stopReplay(){clearInterval(playTimer);state.playing=false;}
function bindLocal(){
 $('event-select')?.addEventListener('change',e=>{stopReplay();state.eventIndex=Number(e.target.value);state.eventDay=0;render();});
 $('event-kind')?.addEventListener('change',e=>{stopReplay();state.eventKind=e.target.value;state.eventIndex=0;state.eventDay=0;render();});
 $('replay-range')?.addEventListener('input',e=>{stopReplay();state.eventDay=Number(e.target.value);render();$('replay-range').focus();});
 $('play-replay')?.addEventListener('click',()=>{if(state.playing){stopReplay();render();return;}if(state.eventDay>=Number($('replay-range').max))state.eventDay=0;state.playing=true;render();playTimer=setInterval(()=>{if(state.route!=='events'||state.eventDay>=Number($('replay-range')?.max??0)){stopReplay();render();return;}state.eventDay++;render();},850);});
 }
async function requestJSON(url){return fetchJSON(url,{force:true});}

async function searchPlace(){const value=$('search-place').value.trim();if(value.length<2){$('search-results').textContent='Enter at least two characters.';return;}const token=renderToken;$('search-button').disabled=true;$('search-results').textContent='Searching Sri Lanka…';try{const j=await requestJSON('https://geocoding-api.open-meteo.com/v1/search?'+new URLSearchParams({name:value,count:'12',language:'en',format:'json',countryCode:'LK'}));state.search=(j.results||[]).filter(x=>x.country_code==='LK');state.searchStatus=state.search.length?'':'No Sri Lankan places found. Try a nearby town.';if(token===renderToken)render();}catch(e){if(token===renderToken){$('search-results').textContent='Search could not connect. Choose a curated monitoring location instead.';$('search-button').disabled=false;}}}
async function refreshWeather(target=loc(),silent=false){
 const id=target.id;const selected=state.loc;const key='floodlens-live-v2';state.liveError='';$('refresh').disabled=true;$('refresh').textContent='Refreshing…';
 try{
  const p=new URLSearchParams({latitude:target.lat,longitude:target.lon,current:'temperature_2m,relative_humidity_2m,wind_speed_10m,pressure_msl',daily:'temperature_2m_max,temperature_2m_min,precipitation_sum,wind_speed_10m_max,precipitation_probability_max',timezone:'GMT',forecast_days:'16'});
  const w=await requestJSON('https://api.open-meteo.com/v1/forecast?'+p);let f=null;let floodError='';
  if(target.river){try{f=await requestJSON('https://flood-api.open-meteo.com/v1/flood?'+new URLSearchParams({latitude:target.lat,longitude:target.lon,daily:'river_discharge_median,river_discharge_p25,river_discharge_p75',forecast_days:'16',models:'forecast_v4'}));}catch(e){floodError='Weather updated; the flood forecast request failed. A prior snapshot may remain.';}}
  state.live=state.live||{weather:{},flood:{},weather_at:{}};state.live.weather[id]=w;state.live.weather_at=state.live.weather_at||{};state.live.weather_at[id]=new Date().toISOString();state.live.origin='API snapshot';if(f){state.live.flood[id]=f;state.live.flood_at=state.live.flood_at||{};state.live.flood_at[id]=new Date().toISOString();}state.liveError=floodError;
  try{localStorage.setItem(key,JSON.stringify(state.live));}catch{}
  if(selected===state.loc){if(!silent)navigate('weather');else if(state.route==='weather'||state.route==='overview')render();notice(floodError);}
 }catch(e){state.liveError='Live refresh failed. Showing the last saved snapshot, if available. Historical analytics are unaffected.';if(selected===state.loc){if(!silent)navigate('weather');notice(state.liveError);}}
 finally{$('refresh').disabled=false;$('refresh').textContent='↻ Refresh weather';}
}
function methodHTML(){return `<p>Historical analysis covers ${dateLabel(summary.start)} to ${dateLabel(summary.end)}. ERA5 supplies older weather; recent IFS values are labelled. GloFAS supplies modelled flow. Upcoming weather and flow come directly from forecast APIs.</p><h3>Historical colours</h3><p>Daily values are compared with the same month in ${esc(summary.baseline_period)} using midrank percentiles. The largest percentile among 3-day rain, flow, heat and wind sets the colour: elevated from the 95th, unusual from the 99th.</p><h3>Forecast signals</h3><p>Daily forecast rainfall and ensemble-median flow are compared with their monthly historical 95th and 99th percentile thresholds. Missing values and snapshots older than 24 hours do not generate flags. No machine-learning model is trained here.</p><h3>Geography and interpretation</h3><p>The real district map provides context. Monitoring points are not district averages. River names indicate vicinity; the exact model channel has not been independently verified. High signals are not confirmed floods, flood probabilities or official warnings.</p><h3>Return-period correction</h3><p>Open-Meteo does not expose 2-, 5- or 20-year flood thresholds. Historical percentiles and forecast ensemble statistics shown here are not return periods.</p><h3>Sources</h3><div class="sources-list">${summary.source_urls.map(u=>`<a href="${u}" target="_blank" rel="noreferrer">${esc(u.replace('https://',''))}</a>`).join('')}<a href="https://www.geoboundaries.org" target="_blank" rel="noreferrer">geoBoundaries district geometry</a><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap attribution</a></div>`;}
function exportCSV(){
 let headers,values;
 if(state.route==='weather'){
  const explorer=state.explorerPlace,d=explorer?.weather?.daily||state.live?.weather?.[state.loc]?.daily;if(!d){notice('Load a forecast before exporting.');return;}
  headers=['date_utc','location','rain_mm','flow_m3s','flow_p25','flow_p75','rain_signal','flow_signal','weather_retrieved_utc','flood_retrieved_utc'];
  const forecast=explorer?forecastSignals(explorer.weather,explorer.flood,null):forecastRows();
  values=forecast.map(r=>[r.date,explorer?.name||loc().name,r.rain,r.q,r.p25,r.p75,r.rainLevel,r.flowLevel,explorer?.retrieved||state.live.weather_at?.[state.loc],explorer?.retrieved||state.live.flood_at?.[state.loc]]);
 }else{headers=['date','location_id','rain','temp','humidity','wind','pressure','tmax','q','r3','r7','qp','rp','tp','wp','severity','weather_model','flow_source'];values=(state.route==='analysis'?allRows():rows()).map(r=>headers.map(k=>k==='location_id'?state.loc:r[k]));}
 if(!values.length){notice('No records are available for this export. Try another date range or refresh the forecast.');return;}
 const quote=v=>`"${String(v??'').replace(/"/g,'""')}"`;const csv=[headers,...values].map(r=>r.map(quote).join(',')).join('\r\n');
 const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=`floodlens-${state.loc}-${state.route}.csv`;a.click();notice(`Download started: ${values.length} records for ${loc().name}. Missing values remain empty.`);setTimeout(()=>URL.revokeObjectURL(url),500);
}
document.addEventListener('click',e=>{const el=e.target.closest('[data-route],[data-location],[data-metric],[data-replay-date],[data-map-mode],[data-date-preset]');if(!el)return;if(el.dataset.mapMode){state.mapMode=el.dataset.mapMode;render();return;}if(el.dataset.datePreset){notice('');state.start=el.dataset.datePreset==='all'?summary.start:el.dataset.datePreset==='year'?summary.end.slice(0,4)+'-01-01':new Date(Date.parse(summary.end+'T00:00:00Z')-29*86400000).toISOString().slice(0,10);state.end=summary.end;$('start-date').value=state.start;$('end-date').value=state.end;render();confirmUpdate();return;}if(el.dataset.route)navigate(el.dataset.route);else if(el.dataset.location)selectLocation(el.dataset.location);else if(el.dataset.metric){state.metric=el.dataset.metric;render();}else if(el.dataset.replayDate){state.eventKind='flood';const cs=eventCandidates();state.eventIndex=Math.max(0,cs.findIndex(x=>x.start<=el.dataset.replayDate&&x.end>=el.dataset.replayDate));state.eventDay=0;navigate('events');}});
document.addEventListener('keydown',e=>{const el=e.target.closest('.map-dot');if(el&&(e.key==='Enter'||e.key===' ')){e.preventDefault();selectLocation(el.dataset.location);}});
async function showSearchedWeather(target){notice(`Loading weather for ${target.name}…`);try{const p=new URLSearchParams({latitude:target.lat,longitude:target.lon,current:'temperature_2m,relative_humidity_2m,wind_speed_10m',daily:'temperature_2m_max,temperature_2m_min,precipitation_sum',timezone:'GMT',forecast_days:'16'});const w=await requestJSON('https://api.open-meteo.com/v1/forecast?'+p);$('method-content').innerHTML=`<h3>${esc(target.name)} · ${esc(target.region)}</h3><p>Current modelled temperature: <strong>${fmt(w.current.temperature_2m)} °C</strong>. Humidity: ${fmt(w.current.relative_humidity_2m,0)}%. Wind: ${fmt(w.current.wind_speed_10m)} km/h.</p><p>Retrieved ${esc(new Date().toLocaleString())}. Forecast days: UTC.</p>${chart([{name:'Forecast rainfall',points:w.daily.time.map((d,i)=>({d,v:w.daily.precipitation_sum[i]}))}],{unit:'mm',bars:false})}<p class="small-note">Historical baselines and river indicators are available for the curated monitoring points only.</p>`;$('method-dialog').showModal();notice('');}catch{notice('Could not retrieve weather for this place. Try a curated location.');}}
window.addEventListener('hashchange',()=>{const requested=location.hash.slice(1),r=requested==='explore'?'weather':requested;if(requested==='explore')history.replaceState(null,'','#weather');if(titles[r]&&state.route!==r){stopReplay();state.route=r;render();}});
$('location').addEventListener('change',e=>selectLocation(e.target.value));$('apply-dates').addEventListener('click',()=>{const a=$('start-date').value,b=$('end-date').value;if(!a||!b||a>b||a<summary.start||b>summary.end){notice(`Choose a valid range between ${summary.start} and ${summary.end}.`);return;}state.start=a;state.end=b;notice('');render();confirmUpdate();});
$('refresh').addEventListener('click',()=>refreshWeather());$('export').addEventListener('click',exportCSV);
for(const id of ['method-link','footer-method'])$(id).addEventListener('click',()=>{$('method-content').innerHTML=methodHTML();$('method-dialog').showModal();});$('close-dialog').addEventListener('click',()=>$('method-dialog').close());
async function init(){try{[summary,geo,baselines,lags]=await Promise.all(['summary.json','districts.geojson','baselines.json','lags.json'].map(f=>requestJSON('data/'+f)));window.floodlensRelease=summary.release_id;await Promise.all(summary.locations.map(async l=>{const j=await requestJSON(`data/${l.id}.json`);data[l.id]=j.rows.map(row=>Object.fromEntries(j.columns.map((c,i)=>[c,row[i]])));}));try{
 state.live=await requestJSON('data/current.json');
 let cached=null;try{cached=JSON.parse(localStorage.getItem('floodlens-live-v2'));}catch{}
 if(cached){for(const kind of ['weather','flood'])for(const id of Object.keys(cached[kind]||{})){
  const at=kind+'_at',cacheTime=Date.parse(cached[at]?.[id]||cached.retrieved_at),bundleTime=Date.parse(state.live[at]?.[id]||state.live.retrieved_at);
  if(Number.isFinite(cacheTime)&&cacheTime>bundleTime){state.live[kind][id]=cached[kind][id];state.live[at]=state.live[at]||{};state.live[at][id]=cached[at]?.[id]||cached.retrieved_at;}
 }}
}catch{try{state.live=JSON.parse(localStorage.getItem('floodlens-live-v2'));}catch{state.live=null;}}

  $('location').innerHTML=summary.locations.map(l=>`<option value="${l.id}">${esc(l.district||l.region)} · ${esc(l.name)}</option>`).join('');for(const id of ['start-date','end-date']){$(id).min=summary.start;$(id).max=summary.end;}state.end=summary.end;state.start=new Date(Date.parse(summary.end+'T00:00:00Z')-89*86400000).toISOString().slice(0,10);$('start-date').value=state.start;$('end-date').value=state.end;const initialRoute=location.hash.slice(1)==='explore'?'weather':location.hash.slice(1);if(titles[initialRoute])state.route=initialRoute;if(location.hash.slice(1)==='explore')history.replaceState(null,'','#weather');render();
}catch(e){$('content').innerHTML=empty('The dataset could not load','Serve this project using START_WINDOWS.bat or python serve.py. Opening index.html directly does not support the data requests. If hosted, reload or contact the project owner.');$('data-badge').textContent='Dataset unavailable';console.error(e);}}
const ready=init();
export {chart,ready,state,render,overview,weather,history,flood,events,quality,selectLocation,navigate};

















let automaticAttempt = 0;
function refreshIfStale(){
 if(document.hidden || navigator.onLine===false || !summary || Date.now()-automaticAttempt<900000)return;
 const stamp=state.live?.weather_at?.[state.loc]||state.live?.retrieved_at;
 if(!stamp || Date.now()-Date.parse(stamp)>900000){automaticAttempt=Date.now();refreshWeather(loc(),true);}
}
ready.then(()=>{window.setInterval(refreshIfStale,60000);window.addEventListener('focus',refreshIfStale);});
